tcc/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from fapesc import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # Examples:
    # url(r'^$', 'tcc_final.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', admin.site.urls),

    url(r'^login/$', views.login, name='login'),
    url(r'^$', views.index, name='index'),
    url(r'^index/', views.index, name='index'),
    url(r'^CadUser/$', views.CadUser, name='CadUser'),
    url(r'^validacao/$', views.validacao, name='validacao'),
    url(r'^sair/$', views.sair, name='sair'),

    #url(r'^area/$', views.caso_area, name='area'),
    url(r'^monitoramento/$', views.monitoramento, name='monitoramento'),
    url(r'^monitoramento/(?P<id_comunidade>\d+)/$', views.monitoramento, name='monitoramento'),

    url(r'^Comunidade/$', views.Comunidade, name='Comunidade'),
    url(r'^Comunidade_Cadastro/$', views.Comunidade_Cadastro, name='Comunidade_Cadastro'),
    url(r'^Comunidade/Edit/$', views.Comunidade_Edit, name='Comunidade_Edit'),
    url(r'^Comunidade/Edit_Campos/$', views.Comunidade_Edit_Campos, name='Comunidade_Edit_Campos'),
    url(r'^Comunidade/Delete/(?P<comu_id>\d+)/(?P<page>\d+)/$', views.Comunidade_Excluir, name='Comunidade_Excluir'),
    url(r'^Comunidade/Permitir/(?P<comu_id>\d+)/(?P<page>\d+)/$', views.Comunidade_Permitir, name='Comunidade_Permitir'),
    url(r'^Comunidade/Utilizar/(?P<comu_id>\d+)/$', views.Comunidade_Utilizar, name='Comunidade_Utilizar'),


    url(r'^Imagem/$', views.Imagem, name='Imagem'),
    url(r'^Imagem_Lista/$', views.Imagem_Lista, name='Imagem_Lista'),
    url(r'^Imagem_Lista/(?P<comu_id>\d+)/$', views.Imagem_Lista, name='Imagem_Lista'),
    url(r'^Imagem_Lista/(?P<comu_id>\d+)/Permitir/(?P<img_id>\d+)/(?P<page>\d+)/$', views.Imagem_Permitir, name='Imagem_Permitir'),
    url(r'^Imagem_Lista/Delete/(?P<img_id>\d+)/(?P<comu_id>\d+)/(?P<page>\d+)/$', views.Imagem_Excluir, name='Imagem_Excluir'),
    url(r'^Imagem_Lista/Permitir/(?P<img_id>\d+)/$', views.Imagem_Permitir, name='Imagem_Permitir'),
    url(r'^Imagem_Lista/Permitir/(?P<img_id>\d+)/(?P<page>\d+)/$', views.Imagem_Permitir, name='Imagem_Permitir'),
    url(r'^Imagem_Lista/Edit/$', views.Imagem_Edit, name='Imagem_Edit'),
    url(r'^Imagem_Lista/Edit_Campos/$', views.Imagem_Edit_Campos, name='Imagem_Edit_Campos'),
    url(r'^Imagem_Cadastro/$', views.Imagem_Cadastro, name='Imagem_Cadastro'),
    url(r'^Imagem_Publica/$', views.Imagem_Publica, name='Imagem_Publica'),
    url(r'^Imagem_Publica/Utilizar/(?P<img_id>\d+)/$', views.Imagem_Utilizar, name='Imagem_Utilizar'),

    url(r'^Casos/$', views.Casos, name='Casos'),
    url(r'^Casos/(?P<caso_id>\d+)/$', views.Casos, name='Casos'),
    url(r'^CadCaso/', views.CadCaso, name='CadCaso'),
    url(r'^Casos/Delete/(?P<caso_id>\d+)/(?P<ob1_id>\d+)/(?P<rel_id>\d+)/(?P<ob2_id>\d+)/$', views.Casos_Excluir, name='Casos_Excluir'),
    url(r'^Caso/Edit/$', views.Caso_Edit, name='Caso_Edit'),
    url(r'^Casos/Edit_Campos/$', views.Caso_Edit_Campos, name='Caso_Edit_Campos'),

    url(r'^cadHistorico/', views.cadHistorico, name='cadHistorico'),
    url(r'^Historico/$', views.Historico, name='Historico'),
    url(r'^Historico/Delete/(?P<hist_id>\d+)/(?P<imagem_id>\d+)/(?P<comu_id>\d+)/(?P<page>\d+)/$', views.Historico_Excluir, name='Historico_Excluir'),
    url(r'^Historico/Delete/Lati/(?P<hist_id>\d+)/(?P<imagem_id>\d+)/(?P<comu_id>\d+)/(?P<page>\d+)/$', views.Historico_Excluir_Lati, name='Historico_Excluir_Lati'),
    url(r'^ComparacaoHist/', views.ComparacaoHist, name='ComparacaoHist'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fapesc/models.py
from django.db import models
import os
from django.conf import settings
from django.contrib.auth.models import User


class relacao(models.Model):
    nome = models.CharField(max_length=128)

    class Meta:
        verbose_name = 'Relacao'
        verbose_name_plural = 'Relacoes'

    def __str__(self):
        return self.nome


class restricao(models.Model):
    descricao = models.CharField(max_length=128)
    distancia = models.IntegerField()

    class Meta:
        verbose_name = 'Restricao'
        verbose_name_plural = 'Restricoes'

    def __str__(self):
        return self.descricao


class objeto(models.Model):
    nome = models.CharField(max_length=128)

    class Meta:
        verbose_name = 'Objeto'
        verbose_name_plural = 'Objetos'

    def __str__(self):
        return self.nome


class usuario(models.Model):
    user = models.ForeignKey(User, blank=True, null=True, editable=False, on_delete=models.CASCADE)
    nome = models.CharField(max_length=128)
    sobrenome = models.CharField(max_length=128)
    dataNasc = models.DateField(blank=True, null=True)
    # rua = models.CharField(max_length=128)
    # numero = models.IntegerField(default=0)
    # bairro = models.CharField(max_length=128)
    # cidade = models.CharField(max_length=128)
    # estado = models.CharField(max_length=128)
    email = models.CharField(max_length=128)
    # formacao = models.CharField(max_length=128)

    class Meta:
        verbose_name = 'Usuario'
        verbose_name_plural = 'Usuarios'


    def __str__(self):
        return self.nome

class comunidade(models.Model):
    nome = models.CharField(max_length=128)
    bairro = models.CharField(max_length=128)
    cidade = models.CharField(max_length=128)
    estado = models.CharField(max_length=128)
    id_usuario = models.ForeignKey(usuario, on_delete=models.CASCADE, null=True)
    permissao = models.CharField(max_length=128, default='N')

    class Meta:
        verbose_name = 'Comunidade'
        verbose_name_plural = 'Comunidades'

    def __str__(self):
        return (self.nome)


class imagem(models.Model):
    img = models.ImageField(upload_to='media/', blank=True)
    usuario = models.ForeignKey(usuario, on_delete=models.CASCADE, null=True)
    dataImagem = models.DateField(blank=True)
    latitude = models.CharField(max_length=128)
    longitude = models.CharField(max_length=128)
    comunidade = models.ForeignKey(comunidade, on_delete=models.CASCADE, null=True)
    permissao = models.CharField(max_length=128, default='N')


    class Meta:
     verbose_name = 'Imagem'
     verbose_name_plural = 'Imagens'

    def __str__(self):
     return str(self.id)

class historico(models.Model):
    usuario = models.ForeignKey(usuario, on_delete=models.CASCADE)
    imagem = models.ForeignKey(imagem, null=True, on_delete=models.CASCADE)
    data = models.DateField(blank=True)
    dataImagem = models.DateField(blank=True, null=True)
    objeto1 = models.CharField(max_length=128)
    lati = models.CharField(max_length=128, null=True)
    longe = models.CharField(max_length=128, null=True)
    relacao = models.CharField(max_length=128)
    objeto2 = models.CharField(max_length=128)
    distancia = models.IntegerField(default=0)
    resultado = models.CharField(max_length=128)
    plano_acao = models.CharField(max_length=128)

    class Meta:
     verbose_name = 'Historico'
     verbose_name_plural = 'Historico'

    def __str__(self):
     return self.plano_acao


class casos(models.Model):
    objeto1 = models.ForeignKey(objeto, related_name="objeto1", null=True, blank=False, on_delete=models.CASCADE)
    relacao = models.ForeignKey(relacao, blank=False, on_delete=models.CASCADE)
    objeto2 = models.ForeignKey(objeto, related_name="objeto2", null=True, blank=False, on_delete=models.CASCADE)
    id_usuario = models.ForeignKey(usuario, on_delete=models.CASCADE)
    distancia = models.IntegerField(default=0)
    restricao = models.ForeignKey(restricao, on_delete=models.CASCADE)
    resultado = models.CharField(max_length=128)
    plano_acao = models.CharField(max_length=128)
    permissao = models.CharField(max_length=128, default='S')

    class Meta:
        verbose_name = 'Caso'
        verbose_name_plural = 'Casos'

    def __str__(self):
        return (self.resultado)

# Create your models here.

templates/imagem/cadastro_imagem.html
<div class="ui modal modalCadImagem">
    <div class="ui segment issem-cad modalpadrao">
        <form action="/Imagem_Cadastro/" method="post">{% csrf_token %}
            <div class="header">
                <i class="ui book default inverted circular icon"></i> Cadastro Imagens
            </div>
            <table class="ui center aligned table">
{#            {{ form.dataImagem }}#}
{#                {{ form.img }}<br>#}
{#                {{ form.latitude }}<br>#}
{#                {{ form.longitude }}<br>#}
                {{file.up}}
{#                <tr>#}
{#                    <td colspan="2">#}
{#                        <select onchange="ativar()" name="comu" id="comu" class="campo_cadastro" required="True">#}
{#                            <option value="selecione">Selecione uma Comunidade</option>#}
{#                            {% for comunidade in comunidades %}#}
{#                                <option value="{{ comunidade.id }}">{{ comunidade.nome }}</option>#}
{#                            {% endfor %}#}
{#                        </select>#}
{#                    </td>#}
{#                </tr>#}
{#                <tr>#}
{#                    <td>Imagem</td>#}
{##}
{#                    <td>Data</td>#}
{#                </tr>#}
{#                <tr>#}
{#                    <td><input type="file" name="imagem" class="campo_cadastro" required></td>#}
{#                    <td><input type="date" name="data" class="campo_cadastro" required></td>#}
{#                </tr>#}
{#                <tr>#}
{#                    <td>Latitude</td>#}
{#                    <td>Longitude</td>#}
{#                </tr>#}
{#                <tr>#}
{#                    <td><input type="text" name="lati" class="campo_cadastro" required></td>#}
{#                    <td><input type="text" name="longi" class="campo_cadastro" required></td>#}
{#                </tr>#}
            </table>
            {% include "blocos/buttons_form.html" %}
        </form>
    </div>
</div>

templates/imagem/imagem.html
{% extends 'base_logado.html' %}

{% block body_block %}
    <div class="ui centered row">
        <div class="ui segment issem-cad">
        <table class="ui striped celled unstackable table" id="tabela_lista">
            <thead>
            <tr>
                <th class="no-sort" colspan="5">
                    <div class="ui default ribbon large label">Administração de Imagem</div>

                </th>
            </tr>
            <tr><td>
                <div class="ui top attached tabular menu">
                        <a class="item" data-tab="first">Suas Imagens</a>
                        <a class="item" data-tab="second">Imagens de Outros Usuários</a>
                    </div>
            </td></tr>
            </thead>
        </table>
        <div class="ui bottom active attached tab segment" data-tab="first">
            <form class="ui form" action="/Imagem_Lista/" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="field">
                    <select onchange="ativar()" name="comu" id="comu" required>
                        <option value="">Selecione uma Comunidade</option>
                        {% for comunidade in comunidades %}
                            <option value="{{ comunidade.id }}">{{ comunidade.nome }} </option>
                        {% endfor %}
                    </select>
                </div>
        <button type="submit" class="ui right labeled icon botaoProximo button" onclick="mostrar_conteudo()" disabled>
            <i class="right arrow icon"></i>
            Ver Imagens dessa Comunidade
        </button>

            </form>
        </div>
        <div class="ui bottom attached tab segment" data-tab="second">
        <form class="ui form" action="/Imagem_Publica/" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="field">
                    <select onchange="ativar()" name="comu" id="comu" required>
                        <option value="">Selecione uma Comunidade</option>
                        {% for comunidade in comu_outros %}
                            <option value="{{ comunidade.id }}">{{ comunidade.nome }} </option>
                        {% endfor %}
                    </select>
                </div>
        <button type="submit" class="ui right labeled icon botaoProximo button" onclick="mostrar_conteudo()" disabled>
            <i class="right arrow icon"></i>
            Ver Imagens Públicas
        </button>

            </form>
        </div>
        </div>
    </div>
{% endblock %}

templates/imagem/imagem_pub.html
{% extends 'base_logado.html' %}
{% block body_block %}

    <div class="ui segment issem-cad modalpadrao">
    <form class="ui form">
        {% csrf_token %}
        <table class="ui striped celled unstackable table" id="tabela_lista">
            <thead>
            <tr>
                <th class="no-sort" colspan="5">
                    <div class="ui default ribbon large label">Comunidade: {{ comu.nome }}</div>
                </th>
            </tr>
            </thead>
        </table>
        <table class="ui striped celled unstackable table" id="tabela_lista">
            <tbody>
            <tr>
                <td>Escolha uma Data:</td>
                <td>Coordenadas Geográficas:</td>
            </tr>
            <tr>
                <td><input type="date" name="data_imagem" class="campo_cadastro" onchange="imagem_pub();" required></td>
                <td>
                    <select onchange="imagem_pub_coor()" name="coor" id="coor" required disabled="True">
                        <option value=''>Selecione uma Coordenada</option>
                    </select>
                </td>
            </tr>
            {#                {% if img %}#}
            </tbody>
        </table>
        <article class="ui centered cards" id="div_img">
            {#         criado por ajax: cards das imagens públicas de outros usuários       #}
        </article>
        <input type="hidden" name="comu_id" value="{{ comu.id }}">
        <table class="ui striped celled unstackable table" id="tabela_lista">
            <tfoot>
            <tr>
                <th colspan="5">
                    <a href="/Imagem/" class="ui left labeled icon secundary button"><i class="left arrow icon"></i>Voltar</a>
                </th>
            </tr>
            </tfoot>
        </table>
    </form>
    </div>

{% include "blocos/modalUtilizar.html" %}
{% endblock %}

templates/imagem/listaImagens.html
{% extends 'base_logado.html' %}
{% load static %}
{% block body_block %}
    <div class="ui segment issem-cad modalpadrao">
        {% csrf_token %}
        <table class="ui striped celled unstackable table" id="tabela_lista">
            <thead>
            <tr>
                <th class="no-sort" colspan="5">
                    <div class="ui default ribbon large label">Lista de Imagens de {{ comunidade.nome }}</div>
                    <button class="right floated ui labeled botaoUpload icon button adicionarImagem">
                        <i class="icon add"></i>
                            Adicionar Imagem
                    </button>
                </th>
            </tr>
            </thead>
        </table>
        <article class="ui centered cards" id="div_img">
            {% if dados %}
                {% for dado in dados %}

                    <div class="ui card">
                        <div class="image">
                            <span id="corner{{ dado.id }}"></span>
                            <img class="imagem_article" src='/media/{{ dado.img }}' >
                        </div>
                        <div class="content">
                            <a class="header">{{ dado.dataImagem }}</a>
                            <div class="item">
                                {{ dado.latitude }} : {{ dado.longitude }}
                            </div>
                            <div class="ui divided list">
                                    {% include 'blocos/editar_excluir.html' %}
                            </div>

                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <div class="ui card">
                    Não há imagens cadastradas.
                </div>
            {% endif %}
        </article>
        <table class="ui striped celled unstackable table" id="tabela_lista">
            <tfoot>
            <tr>
                <th colspan="5">
                    <a href="/Imagem/" class="ui left labeled icon secundary button"><i class="left arrow icon"></i>Voltar</a>
                    <div class="ui right floated pagination secondary menu">
                        {% if dados.has_previous %}
                            <a href="?page={{ dados.previous_page_number }}&comu={{ comunidade.id }}" class="icon item">
                                <i class="left chevron icon"></i>
                            </a>
                        {% endif %}
                        <a class="item">Página {{ dados.number }} de {{ dados.paginator.num_pages }}</a>
                        {% if dados.has_next %}
                            <a href="?page={{ dados.next_page_number }}&comu={{ comunidade.id }}" class="icon item">
                                <i class="right chevron icon"></i>
                            </a>
                        {% endif %}
                    </div>
                </th>
            </tr>
            </tfoot>
        </table>
    </div>
    {% include 'imagem/modalImagem.html' %}
    {% include 'imagem/../blocos/modalPermitir.html' %}

{% endblock %}

templates/imagem/modalEditarImagem.html
<div class="ui modal modalEditarImagem">
    <div class="ui segment issem-cad modalpadrao">
        <form method="POST" name="imagem_form" action="{% url 'Imagem_Edit' %}" class="ui content form">
            {% csrf_token %}
            <div class="header">
                <i class="ui book default inverted circular icon"></i> Editar Imagens
            </div>
            <table class="ui center aligned table">
                <tr>

                    <td>Comunidade</td>
                    <td>Data</td>
                </tr>
                <tr>
                    <td>
                        <select disabled>
                            <option value="{{ dado.comunidade.id }}">{{ dado.comunidade.nome }}</option>
                        </select>
                    </td>
                    <td><input type="date" id="data_img" name="data" class="campo_cadastro" required>
                        <div id="msgdata"></div></td>
                </tr>
                <tr>
                    <td>Latitude</td>
                    <td>Longitude</td>
                </tr>
                <tr>
                    <td><input type="text" id="lati_img" name="lati" class="campo_cadastro" required></td>
                    <td><input type="text" id="longi_img" name="longi" class="campo_cadastro" required></td>
                </tr>
            </table>
            <input type="hidden" name="img_id" id="id_imagem"/>
            {% include "blocos/buttons_form.html" %}
        </form>
    </div>
</div>

templates/imagem/modalExcluirImagem.html
<div class="ui modal modalExcluirImagem">
    <div class="header"><i class="ui warning large circle icon"></i> Excluir Imagem</div>
    <div class="content mensagemExcluir">
        <p>Ao excluir uma Imagem será removido da base de dados Históricos referentes a essa Comunidade.</p>
        <p>Tem certeza que deseja excluir a <b><span id="nome"></span></b> da base de dados?</p>
    </div>
    <div class="actions">
        <div class="ui cancel button">Cancelar</div>
        <a href="#" id="link">
             <div class="ui negative button">Excluir</div>
        </a>

    </div>
</div>

templates/imagem/modalImagem.html
<div class="ui modal modalCadImagem">

    <table class="ui striped celled unstackable table" id="tabela_lista">
        <thead>
        <tr>
            <th class="no-sort" colspan="5">
                <div class="ui default ribbon large label">Cadastrar Imagem</div>
            </th>
        </tr>
        </thead>
    </table>
        <form action="/Imagem_Cadastro/" name="imagem_form" method="post"  enctype="multipart/form-data">{% csrf_token %}
            <div class="modalpadrao">
                <table class="ui center aligned table">
                    <tr>
                        <td colspan="2">
                            <select onchange="ativar()" name="comu" id="comu" class="campo_cadastro" required="True">
                                <option value="{{ comunidade.id }}" selected>{{ comunidade.nome }}</option>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td>Imagem</td>

                        <td>Data</td>
                    </tr>
                    <tr>
                        <td>{{form.img}}</td>
                        <td><input type="date" name="data" class="campo_cadastro" required>
                        <div id="msgdata"></div>
                        </td>

                    </tr>
                    <tr>
                        <td>Latitude</td>
                        <td>Longitude</td>
                    </tr>
                    <tr>
                        <td><input type="text" name="lati" class="campo_cadastro" required></td>
                        <td><input type="text" name="longi" class="campo_cadastro" required></td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <div class="ui slider checkbox">
                                {% if monitorando %}
                                    <input type="checkbox" name="monitorar" checked>
                                {% else %}
                                    <input type="checkbox" name="monitorar">
                                {% endif %}
                                <label>Monitorar</label>
                            </div>
                        </td>
                    </tr>
                </table>
                {% include "blocos/buttons_form.html" %}
        </form>
    </div>
</div>